### ISSUE TITLE
Scenario

### ISSUE THREAD

**Issue by adrienpessu** [bttf-kotlin/kotlin-conf-slides#1]
J'ai commencé à écrire quelques idées du déroulement du talk.

N'hésite pas à commenter, ajouter, préciser, ...

**Comment by jabby** [comment]
J'aime bien l'intro que tu proposes. Je pense qu'il faut par contre séparer distinctement les personnages dans le sens où l'un doit répondre à l'autre. Si l'un propose, l'autre soit abonde dans son sens, soit pose des questions. 

D'ailleurs, je me demandais, qui joue quel rôle au final. J'avais un peu mis les rôle au pif dans le résumé. On peut les inverser. Pour rappel j'avais mis ça : `Doc Gautier et Adrien Mc Fly` mais c'est peut être pas le plus pertinent.

En gros je garderais bien jusqu'à `Doc And Marty are in the past` et je changerais deux trois petites choses,

**Alternative 1:** 

* Doc et Marty vont dans le passé : `git log` **+ screenshot sur un morceau de code sous github**
* Ils découvrent que le cfp est fait en Java et donc est très verbeux
* Doc indique que l'on ne peut pas corriger le bug pour l'avenir en restant sur cette techno. Il propose Kotlin
* Marty lui demande ce que c'est
* Doc indique : **Kotlin ? Mais c'est le back du futur**

Ensuite on débute la présentation.

**Alternative 2:** 

* Doc et Marty vont dans le passé : `git log` **+ screenshot sur un morceau de code sous github**
* Ils découvrent que le cfp est fait en Java et donc est très verbeux
* Marty trouve que c'est trop vieillot et voudrait utiliser
* Doc répond : **Mais bien sûr, Kotlin c'est le back du futur**

Ensuite on débute la conférence,

**Comment by adrienpessu** [comment]
Je préfère l'alternative 2 comme ça les deux connaisent Kotlin, ça sera plus pratique pour le reste de la présentation.

**Comment by jabby** [comment]
Ok. ça me va bien. 
Pour info je travaille sur un petit design pour nos slides. Je pense que ce sera bon dans la semaine. 
Je me mets sur le contenu vendredi.
