### ISSUE TITLE
Thème

### ISSUE THREAD

**Issue by adrienpessu** [bttf-kotlin/kotlin-conf-slides#5]
La partie code du thème est trop petite
La taille des polices est trop petite pour le texte aussi

**Comment by jabby** [comment]
Ok je prends en charge cette semaine. 
Il y a aussi des problèmes de coloration syntaxique. Je me mets dessus. 

- [ ] partie code trop petite
- [ ] taille des textes trop petite
- [x] ajouter la coloration syntaxique

Si tu trouves d'autres choses à améliorer, n'hésite pas à enrichir ce ticket.

**Comment by jabby** [comment]
@adrienpessu Tu peux me donner la résolution de ton écran que je teste chez moi ? En fait, il semble qu'une partie du thème ne soit pas vraiment responsive. Je vais regarder ce point pour corriger. 
Je vais également demander la résolution des vidéoprojecteurs pour le breizhcamp.

**Comment by jabby** [comment]
Résolution au breizhcamp : 1280 x 1024 cf. https://twitter.com/breizhcamp/status/973274385271480322

**Comment by adrienpessu** [comment]
Je suis en 1280x800 mais le plus important c'est vrai que c'est celle du vidéoproj du breizhCamp

**Comment by jabby** [comment]
Si ça peut convenir à toutes les plateformes, ça serait super cool. 
D'ailleurs je viens de tomber sur ça : https://medium.com/myplanet-musings/building-a-responsive-reveal-js-theme-399179632cc6
Y a donc moyen de faire un truc sympa normalement.

**Comment by jabby** [comment]
A noter que j'ai réglé deux autres problèmes. 

- titre OK avec Chrome
- Le gh pages fonctionne correctement maintenant : https://bttf-kotlin.github.io/kotlin-conf-slides/
